discord_token = 'YOUR_DISCORD_TOKEN'
dns_name = 'ACTUAL_SERVER_NAME EX. Hyrule'
port = 'SERVER_PORT_USUALLY_25565'
ip = 'YOUR_IP'
server_name_no_caps = 'ACTUAL_SERVER_NAME_WITHOUT_CAPS EX. hyrule'
server_name = 'SERVER_NAME_WITH_SUFFIX EX. Hyrule.com'
a_certain_user = '<@anumber Google: User Mention Python Discord>'
favicon_github = "for Ex. https://raw.githubusercontent.com/iphex/DPMBot/master/logo.png"
minecraft_server_log = "PATH_TO_YOUR_MINECRAFT_SERVER_LOG EX. D:\\AMPDatastore\\Instances\\Server\\Minecraft\\logs\\latest.log"
owners = 'OwnderID from Discord'
